services:
  web:
    build: ./app
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./app:/app  # Mount local code into the container
    # command: >
    #   uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # Enable hot reload

  mongodb:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
